# Generated by Django 3.1.2 on 2020-11-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20201031_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.IntegerField(default=44665, unique=True),
        ),
    ]
