# Generated by Django 3.1.2 on 2020-11-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20201102_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.IntegerField(default=407320, unique=True),
        ),
    ]
