# Generated by Django 3.1.2 on 2020-10-31 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('blood_group', models.CharField(choices=[('a+', 'A+'), ('o+', 'O+'), ('b+', 'B+'), ('ab+', 'AB+'), ('a-', 'A-'), ('o-', 'O-'), ('b-', 'B-'), ('ab-', 'AB-')], default='', max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10)),
                ('phone_no', models.CharField(default='', max_length=11)),
                ('email', models.EmailField(default='', max_length=254)),
                ('religion', models.CharField(choices=[('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Others', 'Others')], default='', max_length=20)),
                ('reg_no', models.IntegerField(default=596056, unique=True)),
                ('institute_name', models.CharField(default='', max_length=100)),
                ('passing_exam', models.CharField(default='', max_length=100)),
                ('subject_of_interest', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('salary_paid', models.BooleanField(default=False)),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='address.city')),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='address.country')),
            ],
        ),
    ]
