# Generated by Django 3.1.2 on 2020-10-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20201031_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='reg_no',
            field=models.IntegerField(default=3835, unique=True),
        ),
    ]
