# Generated by Django 3.1.2 on 2020-11-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_auto_20201031_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='reg_no',
            field=models.IntegerField(default=67412, unique=True),
        ),
    ]
