# Generated by Django 3.1.2 on 2020-11-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_auto_20201101_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='reg_no',
            field=models.IntegerField(default=492194, unique=True),
        ),
    ]
