# Generated by Django 3.1.2 on 2020-11-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_auto_20201101_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='reg_no',
            field=models.IntegerField(default=632669, unique=True),
        ),
    ]
