# Generated by Django 3.1.2 on 2020-11-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='', max_length=100),
        ),
    ]
